name: build-bundles
run-name: ${{ github.actor }} is bundling documents together
on: [push]
jobs:
  check-bats-version:
    runs-on: docker.io/chgray123/chgray_repro:pandoc
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: ls
      - run: ./tools/PreCheckinUpdate.sh
